In [1]:
import pandas as pd

In [2]:
! pwd

/home/dsc/Data/challenge

## Exercise 3

In [3]:
ls

Amadeus_challenge_2.ipynb  bookings_sample.csv      searches_samples.csv.bz2
Amadeus_challenge.ipynb    bookings_sample.csv.bz2  top_airports.csv
bookings.csv.bz2*          searches.csv.bz2*

In [4]:
bc = pd.read_csv('searches_samples.csv.bz2', sep='^')

In [6]:
pd.set_option('display.max_columns',None)

In [7]:
bc.sample(5)

,Date,Time,TxnCode,OfficeID,Country,Origin,Destination,RoundTrip,NbSegments,Seg1Departure,Seg1Arrival,Seg1Date,Seg1Carrier,Seg1BookingCode,Seg2Departure,Seg2Arrival,Seg2Date,Seg2Carrier,Seg2BookingCode,Seg3Departure,Seg3Arrival,Seg3Date,Seg3Carrier,Seg3BookingCode,Seg4Departure,Seg4Arrival,Seg4Date,Seg4Carrier,Seg4BookingCode,Seg5Departure,Seg5Arrival,Seg5Date,Seg5Carrier,Seg5BookingCode,Seg6Departure,Seg6Arrival,Seg6Date,Seg6Carrier,Seg6BookingCode,From,IsPublishedForNeg,IsFromInternet,IsFromVista,TerminalID,InternetOffice
6721,2013-01-07,01:24:34,MPT,03ffd9c855fe9e61b8d3dc05758967ab,CA,YUL,FLL,1,2,YUL,FLL,2013-03-09,NaN,NaN,FLL,YUL,2013-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,YTO
8654,2013-01-09,11:28:32,MPT,440642a9bdaeb6287f826cefd73255e8,US,ORD,DXB,1,2,ORD,DXB,2013-05-02,VI,NaN,DXB,ORD,2013-05-08,VI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,HPN
5786,2013-01-06,23:32:56,FXP,aa5560258a8882f264d157e15c9997cc,FR,CDG,COK,1,4,CDG,DOH,2013-01-13,BC,H,DOH,COK,2013-01-14,BC,H,COK,DOH,2013-01-20,BC,Q,DOH,CDG,2013-01-20,BC,Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ASI,0,0,0,d41d8cd98f00b204e9800998ecf8427e,PAR
8627,2013-01-09,16:31:22,MPT,440642a9bdaeb6287f826cefd73255e8,US,ATL,BOM,1,2,ATL,BOM,2013-02-09,FK,NaN,BOM,ATL,2013-02-25,FK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,HPN
6569,2013-01-07,09:34:05,MPT,abad92d5dd1f2cea8748bb2013a92ccb,GB,OOL,CHC,1,2,OOL,CHC,2013-03-06,TB,NaN,CHC,OOL,2013-03-14,TB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,LON

In [8]:
bc.columns

Index(['Date', 'Time', 'TxnCode', 'OfficeID', 'Country', 'Origin',
       'Destination', 'RoundTrip', 'NbSegments', 'Seg1Departure',
       'Seg1Arrival', 'Seg1Date', 'Seg1Carrier', 'Seg1BookingCode',
       'Seg2Departure', 'Seg2Arrival', 'Seg2Date', 'Seg2Carrier',
       'Seg2BookingCode', 'Seg3Departure', 'Seg3Arrival', 'Seg3Date',
       'Seg3Carrier', 'Seg3BookingCode', 'Seg4Departure', 'Seg4Arrival',
       'Seg4Date', 'Seg4Carrier', 'Seg4BookingCode', 'Seg5Departure',
       'Seg5Arrival', 'Seg5Date', 'Seg5Carrier', 'Seg5BookingCode',
       'Seg6Departure', 'Seg6Arrival', 'Seg6Date', 'Seg6Carrier',
       'Seg6BookingCode', 'From', 'IsPublishedForNeg', 'IsFromInternet',
       'IsFromVista', 'TerminalID', 'InternetOffice'],
      dtype='object')

In [9]:
bc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 45 columns):
Date                 9999 non-null object
Time                 9999 non-null object
TxnCode              9999 non-null object
OfficeID             9999 non-null object
Country              9999 non-null object
Origin               9999 non-null object
Destination          9999 non-null object
RoundTrip            9999 non-null int64
NbSegments           9999 non-null int64
Seg1Departure        9999 non-null object
Seg1Arrival          9999 non-null object
Seg1Date             9972 non-null object
Seg1Carrier          4047 non-null object
Seg1BookingCode      1143 non-null object
Seg2Departure        7195 non-null object
Seg2Arrival          7195 non-null object
Seg2Date             7160 non-null object
Seg2Carrier          2870 non-null object
Seg2BookingCode      998 non-null object
Seg3Departure        534 non-null object
Seg3Arrival          534 non-null object
Seg3Date             531 non-null object
Seg3Carrier          517 non-null object
Seg3BookingCode      508 non-null object
Seg4Departure        440 non-null object
Seg4Arrival          440 non-null object
Seg4Date             439 non-null object
Seg4Carrier          438 non-null object
Seg4BookingCode      436 non-null object
Seg5Departure        103 non-null object
Seg5Arrival          103 non-null object
Seg5Date             103 non-null object
Seg5Carrier          103 non-null object
Seg5BookingCode      103 non-null object
Seg6Departure        58 non-null object
Seg6Arrival          58 non-null object
Seg6Date             58 non-null object
Seg6Carrier          58 non-null object
Seg6BookingCode      58 non-null object
From                 9924 non-null object
IsPublishedForNeg    9999 non-null int64
IsFromInternet       9999 non-null int64
IsFromVista          9999 non-null int64
TerminalID           9999 non-null object
InternetOffice       9999 non-null object
dtypes: int64(5), object(40)
memory usage: 3.4+ MB